### ISSUE TITLE
Resend the emails whose status is in processing(STATUS_PROCESSING).

### ISSUE THREAD

**Issue by vishalpawar-tudip** [whiteoctober/WhiteOctoberSwiftMailerDBBundle#27]
Hello Team,
I am using SwiftMailerDBBundle to send the messages. Currently, I am facing an issue when trying to resend the messages whose status is in process.
Is there any way to handle those messages (processing, failed) in order to resend it? 
Any help would be really appreciated!!!

**Comment by sampart** [comment]
Hi @vishalpawar-tudip, sorry for the delay in replying.

Have you tried setting the relevant Mail entity's status back to `EmailInterface::STATUS_READY`?  That way the spool should pick it up again.

Hope this helps.  Let me know how you get on.

**Comment by vishalpawar-tudip** [comment]
Thanks @sampart .
Yes, we have coded to pick it up again.
Can we know why the emails are stuck in the spool (processing or failed) status please?
So it will help us to process the email quickly.

**Comment by sampart** [comment]
Hi @vishalpawar-tudip.  It's not possible for me to work out why your mail-sending is failing.

I'd suggest that you manually run the following command (assuming you have some mail in the spool) and see what error output you get:

```
 bin/console swiftmailer:spool:send
```

Good luck troubleshooting!  If the errors suggest that the problem lies with this bundle, please do open a new issue about it.
